/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class work_petrichor_seeta_Detector */

#ifndef _Included_work_petrichor_seeta_Detector
#define _Included_work_petrichor_seeta_Detector
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     work_petrichor_seeta_Detector
 * Method:    detect
 * Signature: (J[BII)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_work_petrichor_seeta_Detector_detect
        (JNIEnv *, jobject, jlong, jbyteArray, jint, jint);

/*
 * Class:     work_petrichor_seeta_Detector
 * Method:    getAddress
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_work_petrichor_seeta_Detector_getAddress
        (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
